spring.application.name=codingshuttelartifacts

server.port=9000

spring.security.debug=true
spring.datasource.url=jdbc:postgresql://localhost:5432/codingshuttle
spring.datasource.username=postgres
spring.datasource.password=Admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

app.jwt.secret=mysupersecretkeymysupersecretkey12345
app.jwt.expiration-ms=86400000
app.jwt.access-ttl-seconds=86400000
app.jwt.refresh-ttl-seconds=864000000

deploy.env=development


